services:
  app1: &app
    #image: rinha2023:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    # expose:
    #   - 8080
    network_mode: host 
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.85GB'
  app2:
    #image: rinha2023:0.0.2
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SERVER_PORT=8081
    depends_on:
      - db
    # expose:
    #   - 8081
    network_mode: host 
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: '0.85GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app1
      - app2
    # ports:
    #   - "80:80"
    #   - "443:443"
    #   - "9999:9999"
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '0.2GB'
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    # expose:
    #   - 5432
    # ports:
    #   - 5432:5432
    network_mode: host
    deploy:
      resources:
        limits:
          cpus: '0.7'
          memory: '1.0GB'
    volumes:
      - type: tmpfs
        target: /dev/shm
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

    #   - POSTGRES_PASSWORD=example